//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.ActionServiceClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActionServiceClient.ISurveyManager")]
    public interface ISurveyManager {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManager/PublishSurvey", ReplyAction="http://tempuri.org/ISurveyManager/PublishSurveyResponse")]
        Epi.Web.Common.DTO.SurveyRequestResponse PublishSurvey(Epi.Web.Common.Message.SurveyRequest pRequestMessage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISurveyManager/GetSurveyInfoById", ReplyAction="http://tempuri.org/ISurveyManager/GetSurveyInfoByIdResponse")]
        Epi.Web.Common.DTO.SurveyInfoDTO GetSurveyInfoById(string pIid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISurveyManagerChannel : Epi.Web.ActionServiceClient.ISurveyManager, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SurveyManagerClient : System.ServiceModel.ClientBase<Epi.Web.ActionServiceClient.ISurveyManager>, Epi.Web.ActionServiceClient.ISurveyManager {
        
        public SurveyManagerClient() {
        }
        
        public SurveyManagerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SurveyManagerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SurveyManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Epi.Web.Common.DTO.SurveyRequestResponse PublishSurvey(Epi.Web.Common.Message.SurveyRequest pRequestMessage) {
            return base.Channel.PublishSurvey(pRequestMessage);
        }
        
        public Epi.Web.Common.DTO.SurveyInfoDTO GetSurveyInfoById(string pIid) {
            return base.Channel.GetSurveyInfoById(pIid);
        }
    }
}
