//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epi.Web.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datasource
    {
        public Datasource()
        {
            this.Canvas = new HashSet<Canva>();
            this.Users = new HashSet<User>();
        }
    
        public int DatasourceID { get; set; }
        public string DatasourceName { get; set; }
        public int OrganizationID { get; set; }
        public string DatasourceServerName { get; set; }
        public string DatabaseType { get; set; }
        public string InitialCatalog { get; set; }
        public string PersistSecurityInfo { get; set; }
        public bool EIWSDatasource { get; set; }
        public Nullable<System.Guid> EIWSSurveyId { get; set; }
        public string DatabaseUserID { get; set; }
        public string Password { get; set; }
        public string DatabaseObject { get; set; }
        public Nullable<bool> SQLQuery { get; set; }
        public string SQLText { get; set; }
        public bool active { get; set; }
        public string portnumber { get; set; }
    
        public virtual ICollection<Canva> Canvas { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
