//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EIWSModel", "FK_SurveyResponse_SurveyMetaData", "SurveyMetaData", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Epi.Web.EF.SurveyMetaData), "SurveyResponse", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Epi.Web.EF.SurveyResponse), true)]

#endregion

namespace Epi.Web.EF
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EIWSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EIWSEntities object using the connection string found in the 'EIWSEntities' section of the application configuration file.
        /// </summary>
        public EIWSEntities() : base("name=EIWSEntities", "EIWSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EIWSEntities object.
        /// </summary>
        public EIWSEntities(string connectionString) : base(connectionString, "EIWSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EIWSEntities object.
        /// </summary>
        public EIWSEntities(EntityConnection connection) : base(connection, "EIWSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyType> SurveyTypes
        {
            get
            {
                if ((_SurveyTypes == null))
                {
                    _SurveyTypes = base.CreateObjectSet<SurveyType>("SurveyTypes");
                }
                return _SurveyTypes;
            }
        }
        private ObjectSet<SurveyType> _SurveyTypes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyMetaData> SurveyMetaDatas
        {
            get
            {
                if ((_SurveyMetaDatas == null))
                {
                    _SurveyMetaDatas = base.CreateObjectSet<SurveyMetaData>("SurveyMetaDatas");
                }
                return _SurveyMetaDatas;
            }
        }
        private ObjectSet<SurveyMetaData> _SurveyMetaDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SurveyResponse> SurveyResponses
        {
            get
            {
                if ((_SurveyResponses == null))
                {
                    _SurveyResponses = base.CreateObjectSet<SurveyResponse>("SurveyResponses");
                }
                return _SurveyResponses;
            }
        }
        private ObjectSet<SurveyResponse> _SurveyResponses;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyTypes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyTypes(SurveyType surveyType)
        {
            base.AddObject("SurveyTypes", surveyType);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyMetaDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyMetaDatas(SurveyMetaData surveyMetaData)
        {
            base.AddObject("SurveyMetaDatas", surveyMetaData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SurveyResponses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSurveyResponses(SurveyResponse surveyResponse)
        {
            base.AddObject("SurveyResponses", surveyResponse);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EIWSModel", Name="SurveyMetaData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyMetaData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyMetaData object.
        /// </summary>
        /// <param name="surveyId">Initial value of the SurveyId property.</param>
        /// <param name="surveyType">Initial value of the SurveyType property.</param>
        /// <param name="closingDate">Initial value of the ClosingDate property.</param>
        /// <param name="surveyName">Initial value of the SurveyName property.</param>
        /// <param name="introductionText">Initial value of the IntroductionText property.</param>
        /// <param name="templateXML">Initial value of the TemplateXML property.</param>
        public static SurveyMetaData CreateSurveyMetaData(global::System.Guid surveyId, global::System.Int32 surveyType, global::System.DateTime closingDate, global::System.String surveyName, global::System.String introductionText, global::System.String templateXML)
        {
            SurveyMetaData surveyMetaData = new SurveyMetaData();
            surveyMetaData.SurveyId = surveyId;
            surveyMetaData.SurveyType = surveyType;
            surveyMetaData.ClosingDate = closingDate;
            surveyMetaData.SurveyName = surveyName;
            surveyMetaData.IntroductionText = introductionText;
            surveyMetaData.TemplateXML = templateXML;
            return surveyMetaData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SurveyId
        {
            get
            {
                return _SurveyId;
            }
            set
            {
                if (_SurveyId != value)
                {
                    OnSurveyIdChanging(value);
                    ReportPropertyChanging("SurveyId");
                    _SurveyId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SurveyId");
                    OnSurveyIdChanged();
                }
            }
        }
        private global::System.Guid _SurveyId;
        partial void OnSurveyIdChanging(global::System.Guid value);
        partial void OnSurveyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SurveyNumber
        {
            get
            {
                return _SurveyNumber;
            }
            set
            {
                OnSurveyNumberChanging(value);
                ReportPropertyChanging("SurveyNumber");
                _SurveyNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SurveyNumber");
                OnSurveyNumberChanged();
            }
        }
        private global::System.String _SurveyNumber;
        partial void OnSurveyNumberChanging(global::System.String value);
        partial void OnSurveyNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SurveyType
        {
            get
            {
                return _SurveyType;
            }
            set
            {
                OnSurveyTypeChanging(value);
                ReportPropertyChanging("SurveyType");
                _SurveyType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurveyType");
                OnSurveyTypeChanged();
            }
        }
        private global::System.Int32 _SurveyType;
        partial void OnSurveyTypeChanging(global::System.Int32 value);
        partial void OnSurveyTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ClosingDate
        {
            get
            {
                return _ClosingDate;
            }
            set
            {
                OnClosingDateChanging(value);
                ReportPropertyChanging("ClosingDate");
                _ClosingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClosingDate");
                OnClosingDateChanged();
            }
        }
        private global::System.DateTime _ClosingDate;
        partial void OnClosingDateChanging(global::System.DateTime value);
        partial void OnClosingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SurveyName
        {
            get
            {
                return _SurveyName;
            }
            set
            {
                OnSurveyNameChanging(value);
                ReportPropertyChanging("SurveyName");
                _SurveyName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SurveyName");
                OnSurveyNameChanged();
            }
        }
        private global::System.String _SurveyName;
        partial void OnSurveyNameChanging(global::System.String value);
        partial void OnSurveyNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OrganizationName
        {
            get
            {
                return _OrganizationName;
            }
            set
            {
                OnOrganizationNameChanging(value);
                ReportPropertyChanging("OrganizationName");
                _OrganizationName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OrganizationName");
                OnOrganizationNameChanged();
            }
        }
        private global::System.String _OrganizationName;
        partial void OnOrganizationNameChanging(global::System.String value);
        partial void OnOrganizationNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DepartmentName
        {
            get
            {
                return _DepartmentName;
            }
            set
            {
                OnDepartmentNameChanging(value);
                ReportPropertyChanging("DepartmentName");
                _DepartmentName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DepartmentName");
                OnDepartmentNameChanged();
            }
        }
        private global::System.String _DepartmentName;
        partial void OnDepartmentNameChanging(global::System.String value);
        partial void OnDepartmentNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IntroductionText
        {
            get
            {
                return _IntroductionText;
            }
            set
            {
                OnIntroductionTextChanging(value);
                ReportPropertyChanging("IntroductionText");
                _IntroductionText = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("IntroductionText");
                OnIntroductionTextChanged();
            }
        }
        private global::System.String _IntroductionText;
        partial void OnIntroductionTextChanging(global::System.String value);
        partial void OnIntroductionTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TemplateXML
        {
            get
            {
                return _TemplateXML;
            }
            set
            {
                OnTemplateXMLChanging(value);
                ReportPropertyChanging("TemplateXML");
                _TemplateXML = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TemplateXML");
                OnTemplateXMLChanged();
            }
        }
        private global::System.String _TemplateXML;
        partial void OnTemplateXMLChanging(global::System.String value);
        partial void OnTemplateXMLChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EIWSModel", "FK_SurveyResponse_SurveyMetaData", "SurveyResponse")]
        public EntityCollection<SurveyResponse> SurveyResponses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SurveyResponse>("EIWSModel.FK_SurveyResponse_SurveyMetaData", "SurveyResponse");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SurveyResponse>("EIWSModel.FK_SurveyResponse_SurveyMetaData", "SurveyResponse", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EIWSModel", Name="SurveyResponse")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyResponse : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyResponse object.
        /// </summary>
        /// <param name="responseId">Initial value of the ResponseId property.</param>
        /// <param name="surveyId">Initial value of the SurveyId property.</param>
        /// <param name="dateLastUpdated">Initial value of the DateLastUpdated property.</param>
        /// <param name="isComplete">Initial value of the IsComplete property.</param>
        /// <param name="responseXML">Initial value of the ResponseXML property.</param>
        public static SurveyResponse CreateSurveyResponse(global::System.Guid responseId, global::System.Guid surveyId, global::System.DateTime dateLastUpdated, global::System.Boolean isComplete, global::System.String responseXML)
        {
            SurveyResponse surveyResponse = new SurveyResponse();
            surveyResponse.ResponseId = responseId;
            surveyResponse.SurveyId = surveyId;
            surveyResponse.DateLastUpdated = dateLastUpdated;
            surveyResponse.IsComplete = isComplete;
            surveyResponse.ResponseXML = responseXML;
            return surveyResponse;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ResponseId
        {
            get
            {
                return _ResponseId;
            }
            set
            {
                if (_ResponseId != value)
                {
                    OnResponseIdChanging(value);
                    ReportPropertyChanging("ResponseId");
                    _ResponseId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ResponseId");
                    OnResponseIdChanged();
                }
            }
        }
        private global::System.Guid _ResponseId;
        partial void OnResponseIdChanging(global::System.Guid value);
        partial void OnResponseIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid SurveyId
        {
            get
            {
                return _SurveyId;
            }
            set
            {
                OnSurveyIdChanging(value);
                ReportPropertyChanging("SurveyId");
                _SurveyId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SurveyId");
                OnSurveyIdChanged();
            }
        }
        private global::System.Guid _SurveyId;
        partial void OnSurveyIdChanging(global::System.Guid value);
        partial void OnSurveyIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateLastUpdated
        {
            get
            {
                return _DateLastUpdated;
            }
            set
            {
                OnDateLastUpdatedChanging(value);
                ReportPropertyChanging("DateLastUpdated");
                _DateLastUpdated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateLastUpdated");
                OnDateLastUpdatedChanged();
            }
        }
        private global::System.DateTime _DateLastUpdated;
        partial void OnDateLastUpdatedChanging(global::System.DateTime value);
        partial void OnDateLastUpdatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DateCompleted
        {
            get
            {
                return _DateCompleted;
            }
            set
            {
                OnDateCompletedChanging(value);
                ReportPropertyChanging("DateCompleted");
                _DateCompleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DateCompleted");
                OnDateCompletedChanged();
            }
        }
        private Nullable<global::System.DateTime> _DateCompleted;
        partial void OnDateCompletedChanging(Nullable<global::System.DateTime> value);
        partial void OnDateCompletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsComplete
        {
            get
            {
                return _IsComplete;
            }
            set
            {
                OnIsCompleteChanging(value);
                ReportPropertyChanging("IsComplete");
                _IsComplete = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsComplete");
                OnIsCompleteChanged();
            }
        }
        private global::System.Boolean _IsComplete;
        partial void OnIsCompleteChanging(global::System.Boolean value);
        partial void OnIsCompleteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ResponseXML
        {
            get
            {
                return _ResponseXML;
            }
            set
            {
                OnResponseXMLChanging(value);
                ReportPropertyChanging("ResponseXML");
                _ResponseXML = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ResponseXML");
                OnResponseXMLChanged();
            }
        }
        private global::System.String _ResponseXML;
        partial void OnResponseXMLChanging(global::System.String value);
        partial void OnResponseXMLChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EIWSModel", "FK_SurveyResponse_SurveyMetaData", "SurveyMetaData")]
        public SurveyMetaData SurveyMetaData
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyMetaData>("EIWSModel.FK_SurveyResponse_SurveyMetaData", "SurveyMetaData").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyMetaData>("EIWSModel.FK_SurveyResponse_SurveyMetaData", "SurveyMetaData").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SurveyMetaData> SurveyMetaDataReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SurveyMetaData>("EIWSModel.FK_SurveyResponse_SurveyMetaData", "SurveyMetaData");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SurveyMetaData>("EIWSModel.FK_SurveyResponse_SurveyMetaData", "SurveyMetaData", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EIWSModel", Name="SurveyType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SurveyType : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SurveyType object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static SurveyType CreateSurveyType(global::System.Int32 id)
        {
            SurveyType surveyType = new SurveyType();
            surveyType.Id = id;
            return surveyType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
    }

    #endregion
    
}
